### ISSUE TITLE
can't get running this boilerplate to now or any other hosting service please help

### ISSUE THREAD

**Issue by muco-rolle** [omarkhatibco/adonis-nextjs-starter#4]

**Comment by omarkhatibco** [comment]
Hi @muco-rolle  
can you provide more information ?
error message ?

**Comment by muco-rolle** [comment]
**this is the trace stack from ZEIT log**
 `Couldn't find a `pages` directory. Please create one under the project root
02/06 10:26 AM (4h)
error Command failed with exit code 1.
02/06 10:26 AM (4h)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
02/06 10:26 AM (4h)
Error: Exited with 1
at ChildProcess.child.on (/tmp/utils/node_modules/@now/build-utils/fs/run-user-scripts.js:11:16)
at emitTwo (events.js:126:13)
at ChildProcess.emit (events.js:214:7)
at maybeClose (internal/child_process.js:925:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
02/06 10:26 AM (4h)
[now] patching https://api-bru1.zeit.co/v2/now/deployments/dpl_4TsN9VwBFrYJ7o915vz8tS4phboN/builds/bld_2ymqehle2 with {"readyState":"ERROR","errorCode":"BUILD_FAILED_2"}``

**Comment by muco-rolle** [comment]
I wanted to create adonisJS + nextJS project separately  like this

```
my_project
        frontend: nextJS 
        backend: adonisJS api
```
and i want to understand how  to deploy this project **this is my first project i'm struggling much**

**Comment by omarkhatibco** [comment]
> I wanted to create adonisJS + nextJS project separately like this
> 
> ```
> my_project
>         frontend: nextJS 
>         backend: adonisJS api
> ```
> and i want to understand how to deploy this project **this is my first project i'm struggling much**

Hi @muco-rolle  
this project is to create adonis and Next together in one project not two.
Try to create 2 project using adonis Cli and create-next-app
