### ISSUE TITLE
Does this support new versions of Adonis and NextJS?

### ISSUE THREAD

**Issue by CodingCreate101** [omarkhatibco/adonis-nextjs-starter#6]
Hi,
since Adonis and NextJS released some updates since the last update of this repo, I was wondering if this still supports new versions of Adonis and NextJS? Like, just by updating package.json maybe?

**Comment by omarkhatibco** [comment]
Hi @CodingCreate101,

I just updated it to the latest versions, it's still working. 

I did not test it with adonis v5 but it should works.

Best Regards 
Omar
